export const elementos = {
  Katon: {
    image: require ('../assets/icons/fogo.png'),
    kanji: '火',
    nome: 'Fogo',
    vence: 'Fuuton',
    perde: 'Suiton',
    corBase: '#Bf0000',
  },
  Fuuton: {
    image: require ('../assets/icons/vento.png'),
    kanji: '風',
    nome: 'Vento',
    vence: 'Raiton',
    perde: 'Doton',
    corBase: '#588083',
  },
  Raiton: {
    image: require ('../assets/icons/trovão.png'),
    kanji: '雷',
    nome: 'Trovão',
    vence: 'Doton',
    perde: 'Fuuton',
    corBase: '#B28009',
  },
  Doton: {
    image: require ('../assets/icons/terra.png'),
    kanji: '土',
    nome: 'Terra',
    vence: 'Suiton',
    perde: 'Katon',
    corBase: '#873e23',
  },
  Suiton: {
    image: require ('../assets/icons/agua.png'),
    kanji: '水',
    nome: 'Água',
    vence: 'Katon',
    perde: 'Raiton',
    corBase: '#3377FF',
  },
};